services:
  traefik:
    image: traefik:v3
    command:
      - "--api.insecure=true"  # Enable dashboard
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--experimental.localPlugins.headerDetection.modulename=github.com/tilak999/traefikplugin"
      #- "--experimental.plugins.myheaderplugin.version=v0.0.7"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"     # HTTP
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/config
      - ./:/plugins-local/src/github.com/tilak999/traefikplugin

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      # Enable your custom plugin
      #- "traefik.http.middlewares.headerPlugin.plugin.headerDetection.headers=x-content-type"
      # Apply the middleware to the router
      - "traefik.http.routers.whoami.middlewares=headerPlugin@file"

networks:
  default:
    name: traefik_network