http:
  middlewares:
    headerPlugin:
      plugin:
        headerDetection:
          dryRun: true
          cloudflarezone: XXXXXXXXXXXXXX
          cloudflaretoken: XXXXXXXXXXXXXXXXXX
          headers: 
            - content-type
            - Content-Length